sid88in/serverless-appsync-plugin

serverless-appsync-plugin/get-config.js, serverless-appsync-plugin/index.js
This adds the `serviceRoleArn` var to get-config's returns,
grabs the missing `userPoolConfig`,
swaps in the `definition` key and gives it Buffer.from(the schema) in createGraphQLSchema(),
and swaps `async.whilst` for `async.until` in monitorGraphQLSchemaCreation()
=> Tighten up deploy a bit

example/serverless.yml, serverless-appsync-plugin/get-config.js, serverless-appsync-plugin/index.js
As a first stab at #25 this uses the `custom.appSync.mappingTemplates` key to explicitly set mappingTemplate details as described in #25, and adds a new key `custom.appSync.mappingTemplatesLocation` for template files location (and still defaults to `mapping-templates`).
=> Map resolver mapping templates

README.md, example/serverless.yml, get-config.js, index.js
Added **2** new commands for the serverless-appsync plugin. 
1.  **update-appsync** 
- Requires you to set an `apiId` in serverless.yml on the appsync config. (Example in the `example/serverless.yml` file) 
- `apiId` should be updated/specified manually every time you deploy a new AppSync API (Maybe this can be automatically updated by the deployment script in the future?)
- Script will automatically create missing data sources and resolvers, if you add more to your serverless.yml file. (Shouldn't have to create a whole new API just to add new data sources/resolvers :P)
2.  **delete-appsync**
- Will delete the AppSync api specified by the `apiId` config in your serverless.yml file.
**Note**:  
- Added a little bit more detailed/visually appealing logging to each of the functions and fixed …
=> Added update-appsync/delete-appsync commands + readme

index.js
A week ago AWS added the supports for a new data source type: `NONE`:
- [Blog: new AWS AppSync features and whitelist removal ](https://aws.amazon.com/blogs/mobile/new-aws-appsync-features-and-whitelist-removal/)
- [API Reference: supported types](https://docs.aws.amazon.com/appsync/latest/APIReference/API_UpdateDataSource.html#API_UpdateDataSource_RequestSyntax)
=> Added support for NONE type data sources'

index.js
```Bash
(node:38968) Warning: a promise was created in a handler at /Users/me/Desktop/repo/app/node_modules/serverless-appsync-plugin/index.js:403:15 but was not returned from it, see http://goo.gl/rRqMUw at new Promise (/Users/me/Desktop/repo/app/node_modules/bluebird/js/release/promise.js:79:10)
````
Technically nothing is wrong. Need to return the callback to avoid this warning.
=> Return Callback To Prevent Warnings

README.md
Make it clear that AWS_IAM as defined [here](https://github.com/sid88in/serverless-appsync-plugin/blob/4273e9d142d426d4be89eecedde6f491dfca0710/get-config.js#L18) is supported as an authentication type.
=> Add AWS_IAM authentication type to readme example

index.js
Closes #118 
I'm appending the types at the end of the schema, seems easier than adding the type in the AST object :)
=> Add AWS scalar types before validating the schema

get-config.js
The previous merged PR #127, also made an addition to the `get-config.js` file which added a local path to the example project schema. Which was breaking deployments as the path to my schema.graphql file was pointing at `../serverless-appsync-plugin/example/`.
**Code Snippet causing issues:**
```
const schemaPath = path.join(
servicePath,
'../serverless-appsync-plugin/example/',
config.schema || 'schema.graphql',
);
```
**Needs to be:**
```
const schemaPath = path.join(
servicePath,
config.schema || 'schema.graphql',
);
```
By deleting this addition, the deployments work again. You can test this break, by updating to the most recent version of the `serverless-appsync-plugin`.
**Break in deployment:**
**Change made in #127:**
=> Fix broken schema.graphql path from previous merged PR

README.md, get-config.js, index.js
It is more like a proposal since the current version does not leverage the full functionality of the serverless variables.
Here is a usage example:
add to the serverless.yml
```
appSync:
...
substitutions:
text: "some text"
localVar: "${self:service.name}"
externalVar: "${cf:${file(../serverless.yml):service.name}-${self:provider.stage}.UserPoolId}"
CloudfrontVar: {'Fn::ImportValue': 'Some-external-stuff'}
```
=> Add support of Serverless variables in velocity templates

__snapshots__/get-config.test.js.snap, get-config.js, get-config.test.js, package.json
When the `substitutions` config is omitted, an error is thrown:
````
Cannot convert undefined or null to object
````
Also fixes Unit tests!
Also, May I suggest that we implement some kind of CI on this repo? e.g: circleci or travis ?
=> Fix error when `substitutions` is omitted + fix Unit tests

.travis.yml, README.md, __snapshots__/get-config.test.js.snap, example/serverless.yml, get-config.js, get-config.test.js, index.js, index.test.js, package.json, yarn.lock
Follow up of #139
**What does it do?**
There is now a new `iamRoleStatements` option for the DataSources.
- When `iamRoleStatements` is present, it will be used to generate the ServiceRole and populate the `ServiceRoleArn` option.
- If `ServiceRoleArn` is already present, `iamRoleStatements` will be ignored and the given `ServiceRoleArn` will be used instead (same behaviour as of now).
- If both are absent, then the plugin will generate a default ServiceRole for the given Data source and give "standard permissions".
(By default it will generate the same Role as if you select "New Role" from the AWS Console:
Any comment or feedback is welcome.
Finally, any help to test this on new and existing stacks would be highly appreciated.
I was not able to test it fully with Elastic Search since I …
=> Implement default serviceRoleArn and custom iamRoleStatements

README.md, index.js
Added support for the AppIdClientRegex parameter in the [AWS AppSync GraphQLApi UserPoolConfig](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appsync-graphqlapi-userpoolconfig.html).
=> Add support for optional parameter appIdClientRegex in user pool config.

README.md
Simple edit to documentation to clarify valid inputs for `type` field in `mappingTemplates`
Closes #110
=> Clarify mapping template type field usage

README.md, index.js, index.test.js
Everywhere that needed an account ID was using the AWS::AccountId
pseudo-parameter [1] instead.
[1] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html
=> Remove unused `accountId` parameter

README.md, index.js
We got the same issue as https://github.com/sid88in/serverless-appsync-plugin/issues/144
After doing some investigations, we found that by changing the hook event in appsync plugin, it will allow the [split stacks plugin](https://github.com/dougmoscrop/serverless-plugin-split-stacks) to work
`stacks-map.js` used by the split stacks plugin
```js
module.exports = {
'AWS::AppSync::ApiKey': { destination: 'AppSync', allowSuffix: true },
'AWS::AppSync::DataSource': { destination: 'AppSync', allowSuffix: true },
'AWS::AppSync::GraphQLApi': { destination: 'AppSync', allowSuffix: true },
'AWS::AppSync::GraphQLSchema': { destination: 'AppSync', allowSuffix: true },
'AWS::AppSync::Resolver': { destination: 'AppSync', allowSuffix: true }
}
```
After deploy
We also tested the deployed appsync and it …
=> Use a different hook for adding resources to allow sls package and the use of other plugins (e.g. split stacks)

README.md, __snapshots__/get-config.test.js.snap, get-config.js, get-config.test.js, index.js, index.test.js
Fixed CloudFormation logicalId changes to prevent migration issues. Please run tests before merging to see if they are satiable to your standards. This should now stop all previous versions of the plugin from deleting resources.
=> Update multiple APIs support

README.md, example/serverless.yml, index.js
Allow userPoolConfig region to override the region specified in the provider section.
=> Issue 178: userPoolConfig in different region does not work

get-stack-value.js, graphql-playground.js, index.js, yarn.lock
Hey! I'm not sure how this ever worked, but async serverless hooks expect a Promise back. I don't really like the "empty Promise hack" to stop if from terminating immediately, but I also couldn't come up with a better solution.
I also updated the call signature of `provider.request()` to stop it from throwing `Serverless: WARNING: Inappropriate call of provider.request()` in debug mode, and noticed that the `yarn.lock` was out of sync.
```bash
Serverless: Invoke graphql-playground
Serverless: WARNING: Inappropriate call of provider.request()
Serverless: WARNING: Inappropriate call of provider.request()
Serverless: WARNING: Inappropriate call of provider.request()
✨  Done in 2.36s.
```
```bash
Serverless: Invoke graphql-playground
koa:application use voyager +0ms
koa:application listen …
```
=> Fix playground

README.md, __snapshots__/get-config.test.js.snap, get-config.js, index.js
Hi,
Amazon recently released the new pipeline resolvers: 
https://aws.amazon.com/blogs/mobile/aws-appsync-releases-pipeline-resolvers-aurora-serverless-support-delta-sync/ 
https://github.com/lkhari and I made these changes to allow for configuring a resolver with a pipeline.
The syntax to test it is: 
```
appSync: 
mappingTemplates:
- type: Query
field: testPipelineQuery
request: 'start.vtl'
response: 'common-response.vtl'
kind: PIPELINE
functions:
- authorizeFunction 
- fetchDataFunction
functionConfigurations:
- dataSource: graphqlLambda
name: 'authorizeFunction'
request: '../mapping-templates/authorize-request.vtl'
response: '../mapping-templates/common-response.vtl'
- dataSource: dataTable
name: 'fetchDataFunction'
request: '../mapping-templates/fetchData.vtl'
response: …
```
=> Pipeline resolver

README.md, index.js
In order to reduce the large file containing all mapping templates I have made this change to allow multiple file inputs. 
I am flattening the input mapping templates into a single array. 
This is tested with 
- array of multiple files
- array of files and mappingtemplates
- nothing
- array of mappingtemplates
I don't believe it will work with files in files though.
Usage example
``` 
appSync:
mappingTemplates:
- ${file(mapping-templates/queries.yml)}
- ${file(mapping-templates/mutation.yml)}
```
=> Allow for nested Mapping Templates

index.js, index.test.js
The BatchGetItem operation is not permitted with default IAM role for DynamoDB, I am not quite sure why.
This adds two allowed actions: `dynamodb:BatchWriteItem` and `dynamodb:BatchGetItem`.
=> Allow batch DynamoDB operations with default role

get-stack-value.js
Not setting the `userPoolConfig.playgroundClientId` in the .yml threw a non descriptive error:
With this PR new error in the console is:
=>  Handle a scenario where value is undefined

README.md
Minor improvement to the documentation by fixing the spelling of Elasticsearch by removing the space between "elastic" and "search" in all occurrences.
=> Remove space in Elasticsearch

index.js
When specifying mapping-templates in `serverless.yml`, the file gets very big very fast.
In most cases, the user wants to use the same structure and naming conventions for all requests and response template. 
If request and response is omitted a default naming convention will be used instead:
`{Type}.{Field}.{Request}.vtl`  and `{Type}.{Field}.{Resonse}.vtl`, This will make the serverless file smaller.
These fields in `serverless.yml`:
```
- field: getSomeData
dataSource: myDatasource
type: Query
- field: putSomeData
dataSource: myDatasource
type: Mutation
- field: getOtherData
dataSource: myDatasource
type: Query
```
Will map by default to:
```
Query.getSomeData.request.vtl
Query.getSomeData.response.vtl
Mutation.putSomeData.request.vtl
Mutation.outSomeData.response.vtl …
```
=> Add default filename conventions for mappingTemplates

index.js
Bug fix for `fn::Sub syntax must contain only alphanumeric characters, underscores, periods, and colons` error that happened if resolver had any special character. This error was also mentioned in #209 and #120.
=> Bug fix for #209 issue in serverless-appsync-plugin.

README.md, example/serverless.yml, index.js, index.test.js
Basically, this will simplify lambda datasources and allow you to do
````yml
- type: AWS_LAMBDA
name: myLambdaDatasource
description: 'My Lambda Datasource'
config:
functionName: myLambda
````
Where `myLambda` is the key name of your lambda in your `serverless.yml`
instead of 
````yml
- type: AWS_LAMBDA
name: myLambdaDatasource
description: 'My Lambda Datasource'
config:
lambdaFunctionArn: { Fn::GetAtt: [MyLambdaLambdaFunction, Arn] }
````
This will also work with [AppSync Emulator](https://github.com/ConduitVC/aws-utils/tree/appsync/packages/appsync-emulator-serverless), and will prevent you from having to do this:
````yml
- type: AWS_LAMBDA
name: myLambdaDatasource
description: 'My Lambda Datasource'
config:
functionName: myLambda
lambdaFunctionArn: { Fn::GetAtt: …
```
=> Simplify lambda datasource config

.travis.yml, README.md, index.js, index.test.js
Currently if you enable logging an AWS role is created with permissions to create a new log group, but because this log group has not been created by serverless as part of the CloudFormation it is not cleaned up/deleted when removing the project.
This will automatically add a log group for AppSync if a `logConfig.level` has been set and also set a log expiry based on [`logRetentionInDays`](https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/) (if set).
=> Added automatic CloudWatch LogGroup creation & deletion with expiry

index.js
before this change error was
ServerlessError: Data Source Type not supported: 'HTTP
after this change it will be
ServerlessError: Data Source Type not supported: HTTP
=> fixing error printout

README.md
Slight adjustment to the pipeline example to make it just a tad more obvious.
=> Small documentation clarification

README.md, __snapshots__/get-config.test.js.snap, get-config.js, index.js, index.test.js
Fixes #241
Since the CloudFormation docs are lacking:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-graphqlapi.html
I used the cli as a reference and followed the same naming conventions:
https://docs.aws.amazon.com/cli/latest/reference/appsync/create-graphql-api.html
example:
```
appSync:
name:
authenticationType: AMAZON_COGNITO_USER_POOLS
additionalAuthenticationProviders:
- authenticationType: AWS_IAM
- authenticationType: OPENID_CONNECT
openIdConnectConfig:
issuer:
clientId:
iatTTL:
authTTL:
```
Still work in progress and I would like some feedback as I don't think I can test all possible scenarios with my setup (I've tested `AMAZON_COGNITO_USER_POOLS` as `authenticationType` and `AWS_IAM` as `additionalAuthenticationProviders`)
I'll update the …
=> Add multiple authorization types support

README.md, index.js
This comment ( from #134 https://github.com/sid88in/serverless-appsync-plugin/issues/134#issuecomment-474145287 ) mentions a regression when ImportValue is used in substitutions and writes [object object] to the resulting VTL.
It looks like it was trying to construct a string of a JS object through string concatenation then JSON.parse'ing it in the next line. So i've kept it as an object throughout.
In testing it looks to work on my project where substitutions are either an ImportValue object or a string:
```
substitutions:
CompanyTableName: { Fn::ImportValue: "CompanyTable-local" }
MasterId: "secretonetwothree"
```
(I've also included the FunctionConfiguration item to the split-stacks documentation as recommended in #243)
=>  Substitions with an ImportValue was writing [object object] to vtl 

README.md, index.js, index.test.js
Implements the `--conceal` argument in the same fashion as the [API Gateway to hide API keys from the output](https://github.com/serverless/serverless/pull/4382).
[Real-world example of it in action](https://github.com/SketchingDev/ServerlessRealtimeReporter/runs/314990393#step:5:53)
```
$ sls deploy
...
appsync api keys:
da2-tjmux5pd4bg28erxnswub4opd4
endpoints:
None
appsync endpoints:
https://bbjffpadibkrgvg6mm5qeoxzhy.appsync-api.us-east-1.amazonaws.com/graphql
```
```
$ sls deploy --conceal
...
appsync api keys:
*** (concealed)
endpoints:
None
appsync endpoints:
https://bbjffpadjffrnmg6mp1keoxgay.appsync-api.us-east-1.amazonaws.com/graphql
```
=> Add option to conceal API keys from output

README.md, __snapshots__/get-config.test.js.snap, __snapshots__/index.test.js.snap, get-config.js, index.js, index.test.js
=> Implement Caching

README.md, src/index.js
Use name for function configurations rather than type / field
Use before/after for pipeline mapping templates rather than request / response
Improve documentation of pipeline mapping templates and function configurations
=> Improved pipeline handling

src/index.js
fixes https://github.com/sid88in/serverless-appsync-plugin/issues/321 — I updated it so that when Appsync functions are created it uses the name specified in the yml file in the `name` field, as opposed to before where it was using the `name` field prefixed with `GraphQlFunctionConfiguration`, which is the resource name.
=> Update Created Function Naming

README.md, __snapshots__/index.test.js.snap, index.test.js, src/index.js
This PR adds the missing permission `rds-data:ExecuteStatement`.
The AppSync tutorial for RDS recommends the following IAM statements:
```
{
"Version": "2012-10-17",
"Statement": [
{
"Effect": "Allow",
"Action": [
"rds-data:DeleteItems",
"rds-data:ExecuteSql",
"rds-data:ExecuteStatement", # Currently missing from this plugin
"rds-data:GetItems",
"rds-data:InsertItems",
"rds-data:UpdateItems"
],
"Resource": [
"arn:aws:rds:us-east-1:123456789012:cluster:mydbcluster",
"arn:aws:rds:us-east-1:123456789012:cluster:mydbcluster:*"
]
},
{
"Effect": "Allow",
"Action": [
"secretsmanager:GetSecretValue"
],
"Resource": [
"arn:aws:secretsmanager:us-east-1:123456789012:secret:mysecret",
"arn:aws:secretsmanager:us-east-1:123456789012:secret:mysecret:*"
]
}
]
}
```
Reference: …
=> Fix IAM statement for RDS

README.md, __snapshots__/index.test.js.snap, index.test.js, src/index.js
This PR gets automatic role generation working, when using elastic search service as a data source, as discussed on #233 
Rather than overload the `endpoint` config key, this PR adds an optional `domain` config key which is to be a reference to a resource of type `AWS::Elasticsearch::Domain`.
If `domain` is provided, `endpoint` no longer needs to be provided - it is automatically derived from the `domain` reference.
This also adds `es:ESHttpPatch` to the list of actions enabled by automatic role generation, since it's one of the 6 basic ones listed in the [AWS docs on ElasticSearch IAM roles](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-ac.html).
I wouldn't view this as a backward-incompatible change because the previous version of this (with the overloaded …
=> Get ElasticSearch automatic role generation working

src/get-stack-value.js, src/graphql-playground.js, src/index.js
This change ensures that the stack name is fetched from serverless' provider.naming object.
It fixes a problem where the playground cannot be started against stacks with "custom" stack names (as opposed to being automatically named by serverless).
=> Update get-stack-value.js to fetch the stackname from provider.naming

src/index.js
It appears #321 broke deployment for projects that are using characters like `.` or `-` in their serverless.yml for function configuration names.
There's already a sanitization function present and in use in this project, this PR just applies it to the function name.
=> Fix for v1.3.0 breaking change: Sanitize function name

README.md
Elaborating on how to attach a resolver to a single field on a custom type.  Showing that not only the standard Query, Mutation and Subscription types can be used.
=> Update readme for dataSource type

__snapshots__/index.test.js.snap, index.test.js, src/index.js
The GraphQL validation function, etc. is all based on GraphQL v14.5.8. Unfortunately there are some key differences between this schema version are the (now quite old) version AppSync uses. This results in cases where the validation step passes, and then the stack update fails.
This patch specifically addresses the three cases I have found (#317):
* AppSync does not support the new style (`""" triple string literal """`) documentation/descriptions
* AppSync does not support old-style (`#`) comments in Enums
* AppSync uses the unofficial comma (install of the standard '&') join for interfaces
I've been using this patch in against our production schema for quite some time, but let me know if you think it's worth integrating.
(I appreciate there's now a GraphQL v15, but that's a whole other …
=> Fix: Triple quote string literal descriptions cause late validation failure

__snapshots__/index.test.js.snap, src/index.js
AppSync's TransactWriteItems now support DynamoDB's ConditionCheck.
It generates the IAM Role needed to run ConditionCheck.
[Resolver Mapping Template Reference for DynamoDB - AWS AppSync](https://docs.aws.amazon.com/appsync/latest/devguide/resolver-mapping-template-reference-dynamodb.html#aws-appsync-resolver-mapping-template-reference-dynamodb-transact-write-items)
[Using IAM with DynamoDB Transactions - Amazon DynamoDB](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/transaction-apis-iam.html)
=> Generate ConditionCheckItem IAM role to support ConditionCheck

README.md
Add a description of the `tags` setting to README.md.
The feature was introduced in #247.
This is the documentation about it.
=> Add documentation about tags to README.md

README.md
`functionConfigurationsLocation` is a useful addition (especially when organizing larger projects).
I thought I'd add it to the documentation so that people can discover it more easily.
=> Documents functionConfigurationsLocation

README.md
Add a description of the X-Ray setting to README.md.
The feature was introduced in #304
This is the documentation about it.
=> Add documentation enable X-Ray to README.md

.github/workflows/ci.yml, .travis.yml, README.md
Travis became slow and most jobs were queued for a long time.
Also, since we have Github Actions, why not using it?!
=> Switch to Github actions

.all-contributorsrc, README.md, __snapshots__/get-config.test.js.snap, __snapshots__/index.test.js.snap, index.test.js, package.json, src/get-config.js, src/index.js, src/utils.js, src/utils.test.js, yarn.lock
Replaces/fixes #373 
Add Api key manager.
Features:
- Allow specifying more than one api key
- Allow custom values for `expiry`, `description` and `apikeyId` (See [Cfn doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-apikey.html)).
- Use names to identify keys.
- Allow op-out of Api key management
=> feat(apiKeys): api keys manager

README.md, __snapshots__/index.test.js.snap, index.test.js, src/index.js
We being required to add documentation to our schema fields in AppSync but the comments are being removed. At
the moment AppSync only supports Old-style comments (#). 
This patch improves this PR ([#340](https://github.com/sid88in/serverless-appsync-plugin/pull/340)) adding the possibility to allow old-style comments (#) to be able to use what is supported in AppSync at least. until the release for the new spec.
I've been using this to release our schemas and is working, let me know if it can be improved. 
1. Added new configuration field `allowHashDescription`
2. Added new method to removeComments from schema
3. Tests
1. use # in your schema to add comments
2. set `allowHashDescription` to true in YAML
3. publish.
=> fix: make hash description optional

README.md, index.test.js, src/index.js
At the moment existing AppSync apis are not supported by the plugin. If there is an existing API in AppSync the plugin will create another one with the same name. 
The proposal is to add back the support of an optional apiId parameter to the Serverless config file. If it is provided then do not create a new AppSync API endpoint but update the existing endpoint instead. This will just update the resources of the existing API and leave the log groups, API URL, API id, authentication provider and the rest of the main stuff unmodified (The auto-generated API URL will not be modified which is important if it is used by some clients and there is no Route53/CloudFront distribution configured).
=> feat: Support updating an existing AppSync API instead of creating a new one

README.md, __snapshots__/get-config.test.js.snap, get-config.test.js, package.json, src/get-config.js, yarn.lock
Support both glob pattern and absolute path for schema.
```
custom:
appSync:
schema:
- path/**/*.graphql
- /path/to/schema.graphql
```
Since all schemas are passing through `mergeTypes` by my implementation, the snapshot has changed a lot.
=> feat: Support glob pattern and absolute path for schema

README.md, __snapshots__/get-config.test.js.snap, __snapshots__/index.test.js.snap, get-config.test.js, index.test.js, src/get-config.js, src/index.js
Made authenticationType attribute optional if user provided the apiId attribute, since it is not used anyway.
It will allow users to create cleaner configs if all they want is to update resources in an existing AppSync API.
Also added 3 more ignored attributes to the README.
And added a log highlighting the same information if user provided an API ID.
Moved the check for the appId attribute to addResources method to make it easier to see from the code where it is used and which attributes are ignored. The ignored attributes are all attributes that modify AppSync API settings.
Updated the unit tests to make sure that the ignored resources are actually ignored.
Tested the creation of a new API and the updates to an existing API.
The attributes are ignored (instead of throwing an exception) …
=> Make authentication type optional when api id is used

src/index.js
Specifies expected types for CLI options to accommodate to recent changes in Serverless Framework (https://github.com/serverless/serverless/blob/master/CHANGELOG.md#2320-2021-03-30)
Closes: #403
=> feat: Add command options schema types

README.md, src/index.js
Closes #402 
The rationale behind this PR is mostly explained in the issue. But here is another tl;dr:
```garphql
type Test @cognito_user_pool {
field: Strin
}
```
The example above (has missing `aws_` prefix in auth directive as well as typo in String type) passes the old validation but fails the new one.
Added config option `validatieSyntaxOnly` which falls back to previous validation behavior. This can be used as an escape hatch until the stubs are updated in case appsync adds new types or changes the existing ones.
=> Use buildASTSchema for validation

src/get-config.js
Fixes #404 
The issue is caused by `globby` not working with windows paths as patterns. More precisely `fast-glob` which is what `globby` is based on does not support windows paths as patterns and it seems to be intentional, so I don't think it will change anytime soon. `fast-glob` recommends [replacing `\\` with `/`](https://github.com/mrmlnc/fast-glob#how-to-write-patterns-on-windows) so I did that and it worked.
=> Fix schema path globbing on Windows

README.md, __snapshots__/index.test.js.snap, index.test.js, src/index.js
This PR adds support for adding Managed Rule Groups  in WAF.
See https://github.com/sid88in/serverless-appsync-plugin/issues/412 for a discussion of the problem.
I've manually tested the configuration with this YAML:
```
wafConfig:
rules:
- name: MyRule1
overrideAction:
none: {}
statement:
managedRuleGroupStatement:
vendorName: AWS
name: AWSManagedRulesCommonRuleSet
```
=> Fix: add support for Managed Rule Groups in WAF

README.md, __snapshots__/index.test.js.snap, index.test.js, src/get-config.js, src/index.js
Last week, AWS released a new way to authorize AppSync APIs, using Lambda functions like in API Gateway.
[Blog Post here 🔗](https://aws.amazon.com/blogs/mobile/appsync-lambda-auth/)
@sweepy84 mentioned this in that issue (#425).
This pull currently covers only the deployment functionality, allow you to setup the Lambda Authorizer in the `serverless.yml` and deploy to the cloud.
I'm not too familiar with the graphql-playground, cause we use another plugin to execute and test locally here, so I glad if someone could help to implement that too. 😃
This is a snippet how to set up the LAMBDA authorizer. You can refer the function logical name (defined in `functions:`) using the `functionName` field, or pass the Arn directly, (or using the intrinsic function `Fn:GetAtt` to get the Arn).
The …
=> feat: aws lambda authorizer

__snapshots__/get-config.test.js.snap, __snapshots__/index.test.js.snap, index.test.js, src/index.js
The substitutions feature is nice and really helpful, but it couldn't substitute values such as `false`, `""`, and `0`.
This PR fixes that.
=> Fix substitutions from "falsy" values

.gitignore
In #439, yarn-error.log was pushed by mistake, so add it to .gitignore.
=> chore: add yarn-error.log to .gitignore

package-lock.json, package.json, src/__tests__/api.test.ts, src/__tests__/fixtures/schemas/multiple/post.graphql, src/__tests__/fixtures/schemas/multiple/schema.graphql, src/__tests__/fixtures/schemas/multiple/user.graphql, src/__tests__/fixtures/schemas/single/schema.graphql, src/__tests__/schema.test.ts, src/index.ts, src/resources/Schema.ts
- Force using modern GraphQL schemas in v2
- Plugin will NOT try to "fix" the schemas to be compatible with AppSync
- types extending multiple interfaces must use `&` (AppSync will fix)
- `"""` will be kept as-is. AppSync will drop them. Appsync might also fail when used with `enum`
- `#` will be removed from schema when merged
- Exception: Appsync does not support [Object extensions](https://spec.graphql.org/October2021/#sec-Object-Extensions). The plugin will merge all the types into one using "official" [utilities](https://graphql.org/graphql-js/utilities/)
- Escape hatch: Single files will be kept as-is.
=> Use modern GraphQL schemas

README.md, index.test.js, src/index.js
It caught me by surprise that [MaxBachSize](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-resolver.html#cfn-appsync-resolver-maxbatchsize) is not supported.
My project recently reached a point where we are actively exploring ways to squeeze out the last bits of performances, [batching](https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-lambda-resolvers.html#advanced-use-case-batching) is definitely something worth trying.
It is also allowed in [Direct Lambda Resolvers](https://docs.aws.amazon.com/appsync/latest/devguide/resolver-mapping-template-reference-lambda.html#direct-lambda-resolvers), scroll down to the section **Direct Lambda Resolvers: Batching enabled** to read more.
=> feat: support MaxBatchSize

README.md
As I understand this plugin works at the build stage and may be installed as a dev dependency.
=> docs: recommend to install as dev dependency

src/__tests__/__snapshots__/dataSources.test.ts.snap, src/__tests__/dataSources.test.ts, src/resources/DataSource.ts
When defining 
```
dataSources:
tableDataSource:
type: AMAZON_DYNAMODB
description: 'Main table events for everything. Events, users, guests.'
config:
tableName: !Ref Table
```
The generated IamRoleStatement is:
```
"Resource": [
"arn:aws:dynamodb:eu-west-1:679049160385:table/[Object object]",
"arn:aws:dynamodb:eu-west-1:679049160385:table/[Object object]/*"
],
```
This PR fixes that issue.
=> fix: generate correct dynamodb IamStatement

README.md, __snapshots__/index.test.js.snap, index.test.js, src/index.js, yarn.lock
closes #500 
Example serverless configuration:
```yml
wafConfig:
enabled: true
arn: arn:aws:waf-regional:<region>:<account-id>:rule/<rule-id>
```
=> feat: support associating WAF without creating

index.test.js, src/index.js
AWS Cloudformation allows us to set Sync Configuration to functionConfigurations (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-functionconfiguration.html#cfn-appsync-functionconfiguration-syncconfig) but the package was not really dealing with it and generating the correct code for it.
So I basically copied the code that was parsing this in the Mapping Templates to the function configuration so it works there too. Also, I've tried to add some basic unit testing. Sorry if I'm not following any patterns on the coding! =)
Please let me know if you need any more changes here so this get approved and to production.
=> feat(pipelineFunctions): Added the sync options

doc/upgrading-from-v1.md
Hey and congrats on the v2 launch! 🥳  I found a couple of spelling errors in the upgrade guide when I was going through it.
=> docs: Fix spelling errors in upgrade guide

src/__tests__/validation/__snapshots__/auth.test.ts.snap, src/__tests__/validation/auth.test.ts, src/validation.ts
[Documentation](https://github.com/sid88in/serverless-appsync-plugin/blob/master/doc/authentication.md#oidc) states that `clientId` is optional for OIDC, however, the validation in place makes it required. This PR fixes this by making `clientId` optional.
=> fix: make oidc clientId optional

README.md, doc/pipeline-functions.md, doc/resolvers.md, doc/substitutions.md
- Removed duplicated code examples on substitutions.md
- Added Example for JS Resolvers
- Updated Links to substitutions.md to display `Variable Substitutions` instead of `VTL template substitutions`
=> docs: Added Substitution example for JS Resolvers

doc/resolvers.md, src/__tests__/resolvers.test.ts, src/resources/Resolver.ts, src/types/plugin.ts
Added support javascript runtime for unit resolver.
https://aws.amazon.com/jp/blogs/mobile/aws-appsync-now-supports-javascript-for-all-resolvers-in-graphql-apis/
Closes #616
=> feat: support js runtime for unit resolver

doc/resolvers.md
`kind: UNIT` was missing from the documentation and has cost me quite a bit of time to figure it out, so I should it'd add it. 🤓
=> doc: Fix Resolver example

src/__tests__/resolvers.test.ts, src/resources/Resolver.ts
This fixes a regression introduced in `v2` where the per-resolver caching TTL defaults to `3600` even when a global caching TTL is defined.
=> fix: use global caching TTL by default in resolver caching config

doc/WAF.md, src/__tests__/__snapshots__/waf.test.ts.snap, src/__tests__/waf.test.ts, src/resources/Waf.ts
Fix for https://github.com/sid88in/serverless-appsync-plugin/issues/578.
When v1 to v2 migration, overrideAction in WAF code was missed to migrate.
override action is typically `None: {}`, or `Count : {}`
https://docs.aws.amazon.com/waf/latest/APIReference/API_OverrideAction.html
I referred around this code in v1 branch.
If `overrideAction` is set, use `overrideAction`. Otherwise, `Action` is used same as before.
https://github.com/sid88in/serverless-appsync-plugin/blob/v1.14.0/src/index.js#L1612
tested with AWS
- cloud formation was generated same as v1
- `sls deploy` suceeded
```
"Name": "AWSManagedRulesCommonRuleSet",
"Priority": 20,
"Statement": {
"ManagedRuleGroupStatement": {
"VendorName": "AWS",
"Name": "AWSManagedRulesCommonRuleSet"
}
},
"VisibilityConfig": { …
```
=> fix : support overrideAction for WAF

src/resources/Schema.ts
After updating to serverless v4 I ran into an issue where the generated schema was always empty.
We are using serverless-compose, so we have a folder structure like this:
```
services/
service-1/
serverless.yml
service-2/
serverless.yml
serverless-compose.yml
```
It seems that the schema files are paths relative to the service directory, but the `cwd` is the root folder, thus none of the schema files can be found. 
This PR should fix that problem and also resolve #648.
=> fix: incorrect path to schema

.github/workflows/ci.yml
This PR adds PR verification with newer Node.js versions 20, 22, 24, 26.
=> ci: add newer nodejs version

.github/workflows/ci.yml, .github/workflows/release.yml
The setup-node@v3 and checkout@v3 are outdated, the latest version is 5. This PR updates action dependencies versions.
=> chore: update actions versions
