sid88in/serverless-appsync-plugin

README.md
This adds steps to use to the readme.
=> Add steps to use to readme

.gitignore, README.md, index.js, package.json
- Added cleanupDataSources that removes any unused data sources when updating. For example if you have a data source called `Lambda` on your API and it isn't defined in your serverless.yml file .. it will be deleted. 
Updated to 0.0.4
=> v0.0.4 - Added cleanupDataSources function

README.md, index.js, package.json
this PR adds functionality to update API key
=> update api key

get-config.js, get-config.test.js, index.js
This change:
- formats code to follow eslint
- fixes two catch errors where the log was using a nonexistent variable
I would be very happy to see prettier used instead :) :)
=> follow eslint rules

example/handler.js, example/webpack.config.js, index.js, package.json
=> add linter

README.md, get-config.js, index.js
Resolves sid88in/serverless-appsync-plugin#89
=> Add logConfig settings for AppSync API Logging

README.md, get-config.js, index.js, package.json
This code, while it looks correct, does not appear to work due to a problem with AppSync/Cloudformation.
See this: https://forums.aws.amazon.com/thread.jspa?threadID=283342
=> Add support for OPENID_CONNECT

index.js
=> Use global substition for getCfnName regex

index.js
=> Add support for resolvers with same field name within different types

README.md
give a short intro on how to use the offline plugin
=> add intro to serverless-appsync-offline plugin

__snapshots__/get-config.test.js.snap, get-config.js, index.js, index.test.js
Reverts sid88in/serverless-appsync-plugin#155
+ @ZY-Ang
=> Revert "Add support for Multiple APIs"

index.js
Should be GraphQlApi, not GraphQLApi
=> Fix RESOURCE_API typo

README.md, index.js
Solves https://github.com/sid88in/serverless-appsync-plugin/issues/197
=> Cognito's userPoolConfig.defaultAction is a required property

package.json, yarn.lock
Fixes https://github.com/sid88in/serverless-appsync-plugin/issues/165
=> add missing aws-sdk dependency

index.js, package.json, yarn.lock
Now displaying useful info in the stack output.
Fixes #212
=> Improve stack output

README.md, __snapshots__/get-config.test.js.snap, example/_type_tweet.graphql, example/_type_user.graphql, get-config.js, get-config.test.js, package.json, yarn.lock
Support for multiple schema files as an array in the config
```yml
custom:
appSync:
schema:
- path/to/schema_base.graphql
- path/to/schema_internal.graphql
```
Inspired by #62.
=> Support for multiple schema files

index.js
Resolves #254 
Tested on a full deployment and worked.
=> Exposes AppSync API ID as CF Stack Output

README.md, src/index.js
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appsync-graphqlapi-logconfig.html#cfn-appsync-graphqlapi-logconfig-excludeverbosecontent
=> added ExcludeVerboseContent to LogConfig

README.md, __snapshots__/index.test.js.snap, index.test.js, src/index.js
=> Delta sync config

__snapshots__/get-config.test.js.snap, package.json, src/get-config.js, yarn.lock
For fix #346 
I referred to this page
https://www.graphql-tools.com/docs/migration-from-merge-graphql-schemas
There are differences in the test snapshots, but it works.
This commit seems to fix existing spacing problem.
=> replace merge-graphql-schema to @graphql-tools/merge

README.md
=> Fix an important typo in README.md

README.md, __snapshots__/index.test.js.snap, index.test.js, src/index.js
Folow up of https://github.com/sid88in/serverless-appsync-plugin/pull/363
=> Sync config

.all-contributorsrc, README.md, __snapshots__/index.test.js.snap, index.test.js, src/index.js
=> Support `functionAlias` in lambda data sources.

README.md, index.test.js, src/index.js
Referencing Issue #390, This allows cross-stack reference to be able to use `Fn::ImportValue` in other CF stacks.
=> Export the stack outputs

src/index.js
=> Add @aws_subscription directive to aws types stubs

README.md
=> doc: Fix typos

package-lock.json, package.json, src/__tests__/fixtures/schemas/multiple/post.graphql, src/__tests__/fixtures/schemas/multiple/user.graphql, src/__tests__/schema.test.ts, src/resources/Schema.ts
- Keep AppSync directives in schema
- Allow AppSYnc custom Scalars
=> Fix: schema merging & AppSync Scalars

README.md
Was just reading the docs for offline support and found this typo :)
=> docs(offline): fix typo in Readme about offline support libraries

src/__tests__/validation/__snapshots__/auth.test.ts.snap, src/__tests__/validation/auth.test.ts, src/types/plugin.ts, src/validation.ts
=> fix(validation): Cognito auth validation

src/__tests__/js-resolvers.test.ts, src/resources/JsResolver.ts, src/resources/PipelineFunction.ts, src/resources/Resolver.ts
I've just copy/pasted the MappingTemplate.ts file and did all required refactors. I'm going to test it on my project.
=> Implement substitutions for js resolvers

.github/workflows/ci.yml, src/__tests__/api.test.ts, src/resources/Api.ts
=> fix(auth): Cognito additional auth

README.md, doc/upgrading-from-v1.md
This will force a major version bump.
=> Prepare v2 release 🚀 

doc/API-keys.md, doc/authentication.md, doc/commands.md
Hey! Found a few errors in the documentation
=> docs: correct invalid documentation

.eslintrc.js, README.md, doc/WAF.md, doc/authentication.md, doc/caching.md, doc/custom-domain.md, doc/dataSources.md, doc/general-config.md, doc/pipeline-functions.md, doc/substitutions.md, src/index.ts
Heyo, went over and fixed some more spelling errors while I was at it
=> docs: fix spelling errors

doc/dataSources.md, src/__tests__/__snapshots__/dataSources.test.ts.snap, src/__tests__/dataSources.test.ts, src/__tests__/validation/__snapshots__/datasources.test.ts.snap, src/__tests__/validation/datasources.test.ts, src/resources/DataSource.ts, src/types/cloudFormation.ts, src/types/plugin.ts, src/validation.ts
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appsync-datasource-eventbridgeconfig.html
=> feat(dataSources): Add Support for EventBridge DataSource

doc/upgrading-from-v1.md
I've added some info on the API key rotation issue and steps to mitigate it.
Addresses https://github.com/sid88in/serverless-appsync-plugin/issues/584
=> Add info about API key rotation issue during migration

src/resources/Schema.ts
=> fix: lint issue

package.json
This PR adds supported engines to the package.json
=> chore: add engines

src/resources/Api.ts
When roleArn is provided it will be used and new role will not be created.
=> when role arn provided it will be used
